---
title: "Simulation"
author: "Yanruyu Zhu (yaz4004)"
date: "10/28/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# First try-out         
- 10/28/2021      
- DLT = 0.2; Scenario 10; local BOIN; Sim=10,000;             
- Cohort size = 3        
- Dose level = 5
```{r}
# make sure all the data diles and Rmd files are in the same folder
path = getwd()
setwd(path)

for (package in c('readxl', 'BOIN', 'escalation')) {
    if (!require(package, character.only=T, quietly=T)) {
        install.packages(package)
        library(package, character.only=T)
    }
}

DLT_15 = as.data.frame.list(read_excel("ToxicityScenarios_DLTrates.xlsx", sheet = "DLT=0.15"))
DLT_20 = as.data.frame.list(read_excel("ToxicityScenarios_DLTrates.xlsx", sheet = "DLT=0.2"))
DLT_25 = as.data.frame.list(read_excel("ToxicityScenarios_DLTrates.xlsx", sheet = "DLT=0.25"))
DLT_30 = as.data.frame.list(read_excel("ToxicityScenarios_DLTrates.xlsx", sheet = "DLT=0.3"))
```

```{r}
DLT_20
S10 = DLT_20[DLT_20$Scenario==10,][2:6]
DLT_true = 0.2
S10 = as.double(as.list(S10))

```

### - Local BOIN           

```{r}
### Try "Local BOIN" on Scenario 10 
result = get.oc(target = DLT_true, p.true = S10,
                ncohort=10, cohortsize=3, startdose=1, ntrial=10000)
result
```


```{r}
PCS_lis = rep(0,16)
for (i in 1:nrow(DLT_20)) {
  S = as.list(DLT_20[DLT_20$Scenario==i,][2:6])
  result = get.oc(target = DLT_true, p.true = as.double(S),
                ncohort=10, cohortsize=3, startdose=1, ntrial=10000)
  idx = which(S == DLT_true)[1]
  PCS_lis[i] = result$selpercent[idx]
}

#result = get.oc(target = DLT_true, p.true = S10,
#                ncohort=10, cohortsize=3, startdose=1, ntrial=1000)
```


```{r}
plot(x = (1:16), y = PCS_lis, type="o", pch="o", lty=1, ylim=c(0,70),
     xlab="Scenario",
     ylab="Correct Selection",
     main="Local BOIN PCS when DLT=0.2")
```

### - 3+3      
```{r}
### Try "3+3" on Scenario 10 
sims <- get_three_plus_three(num_doses = 5, allow_deescalate = FALSE) %>%
  simulate_trials(num_sims = 1000, true_prob_tox = as.double(S10))
sims
```


```{r}
# Plot on DLT=0.2
PCS_lis_3plus3 = rep(0,16)
for (i in 1:nrow(DLT_20)) {
  S = as.list(DLT_20[DLT_20$Scenario==i,][2:6])
  #result = get.oc(target = DLT_true, p.true = S,
  #              ncohort=10, cohortsize=3, startdose=1, ntrial=10000)
  sims <- get_three_plus_three(num_doses = 5, allow_deescalate = FALSE) %>%
  simulate_trials(num_sims = 10000, true_prob_tox = as.double(S))
  idx = which(S == DLT_true)[1]
  PCS_lis_3plus3[i] = prob_recommend(sims)[idx+1]
  #PCS_lis[i] = result$selpercent[idx]
}

```

```{r}
plot(x = (1:16), y = PCS_lis_3plus3*100, type="o", pch="*", lty=1, ylim=c(0,70),
     xlab="Scenario",
     ylab="Correct Selection",
     main="3+3 PCS when DLT=0.2")
```

## Performance metrics      
### - i. Compare 3+3 vs Local BOIN on PCS      

#### DLT = 15%        
```{r}
PCS_lis_15 = rep(0,16)
for (i in 1:nrow(DLT_20)) {
  S = as.list(DLT_20[DLT_20$Scenario==i,][2:6])
  result = get.oc(target = DLT_true, p.true = as.double(S),
                ncohort=10, cohortsize=3, startdose=1, ntrial=10000)
  idx = which(S == DLT_true)[1]
  PCS_lis[i] = result$selpercent[idx]
}

plot(x = (1:16), y = PCS_lis, type="o", pch="o", lty=1, col="black",
     xlim = c(1,16), ylim=c(0,100), axes=FALSE,
     xlab="Scenario",
     ylab="Correct Selection (%)",
     main="Target DLT rate = 20%")

axis(side = 1, at = seq(1, 16, by=1), las=2)
axis(side = 2, at = seq(0, 100, by=10))
lines(x = (1:16), PCS_lis_3plus3*100, pch=18, col="blue", type="b", lty=2)
legend(x = "topleft", legend=c("Local BOIN", "3+3"),
       col=c("black", "blue"), lty=1:2, lwd=2)
```


#### DLT = 20%        
```{r}
plot(x = (1:16), y = PCS_lis, type="o", pch="o", lty=1, col="black",
     xlim = c(1,16), ylim=c(0,100), axes=FALSE,
     xlab="Scenario",
     ylab="Correct Selection (%)",
     main="Target DLT rate = 20%")

axis(side = 1, at = seq(1, 16, by=1), las=2)
axis(side = 2, at = seq(0, 100, by=10))
lines(x = (1:16), PCS_lis_3plus3*100, pch=18, col="blue", type="b", lty=2)
legend(x = "topleft", legend=c("Local BOIN", "3+3"),
       col=c("black", "blue"), lty=1:2, lwd=2)
```

### - ii. The average number of patients allocated to the MTD       
#### DLT = 20%
```{r}
PCS_lis
for (i in 1:nrow(DLT_20)) {
  S = as.list(DLT_20[DLT_20$Scenario==i,][2:6])
  result = get.oc(target = DLT_true, p.true = as.double(S),
                ncohort=10, cohortsize=3, startdose=1, ntrial=10000)
  idx = which(S == DLT_true)[1]
  PCS_lis[i] = result$selpercent[idx]
}
```


### Set-up parameters      
### Toxicity scenario generation         
true toxicity probabilities           
(P11) Paoletti, O’Quigley and Maccario (2004)   

```{r}
# target toxicity rate
phi = 0.25
# probability simulation parameters
sigma0 = 0.05
sigma1 = 0.35
sigma2 = 0.35
mu1 = 0.15
mu2 = 0.15
```

```{r}
p_j_min1 <- function(p_j, phi, sigma1, mu1) {
  z_p_j = qnorm(p_j,0,1)
  z_2phiMinpj = qnorm(2*phi-p_j)
  z_phi = qnorm(phi, 0, 1) # z(phi)
  I = (z_p_j > z_phi)
  e_j_min1 = rnorm(1, mu1, sigma1)
  p_j_min1 = pnorm(z_p_j - (z_p_j - z_2phiMinpj)*I - e_j_min1^2, 0, 1)
  return(p_j_min1)
}

p_j_plus1 <- function(p_j, phi, sigma2, mu2) {
  z_p_j = qnorm(p_j,0,1)
  z_2phiMinpj = qnorm(2*phi-p_j)
  z_phi = qnorm(phi, 0, 1) # z(phi)
  I = (z_p_j < z_phi)
  e_j_plus1 = rnorm(1, mu2, sigma2)
  p_j_plus1 = pnorm(z_p_j + (z_2phiMinpj - z_p_j)*I + e_j_plus1^2, 0, 1)
  return(p_j_plus1)
}

p_j_min2 <- function(p_j_min1, sigma1, mu1) {
  z_p_jmin1 = qnorm(p_j_min1, 0, 1)
  e_j_min2 = rnorm(1, mu1, sigma1)
  p_j_min2 = pnorm(z_p_jmin1 - e_j_min2^2)
  return(p_j_min2)
}

p_j_plus2 <- function(p_j_plus1, sigma2, mu2) {
  z_p_jplus1 = qnorm(p_j_plus1, 0, 1)
  e_j_plus2 = rnorm(1, mu2, sigma2)
  p_j_plus2 = pnorm(z_p_jplus1 + e_j_plus2^2)
  return(p_j_plus2)
}

prob_list <- function(j,p_j,p_lis,phi,sigma1,sigma2,mu1,mu2){
  p_lis[j] = p_j
  if (j == 1) {
    p_lis[2] = p_j_plus1(p_j, phi, sigma2, mu2)
    p_lis[3] = p_j_plus2(p_lis[2], sigma2, mu2)
    p_lis[4] = p_j_plus2(p_lis[3], sigma2, mu2)
    p_lis[5] = p_j_plus2(p_lis[4], sigma2, mu2)
    } 
  else if (j == 2) {
    p_lis[1] = p_j_min1(p_j, phi, sigma1, mu1)
    p_lis[3] = p_j_plus1(p_j, phi, sigma2, mu2)
    p_lis[4] = p_j_plus2(p_lis[3], sigma2, mu2)
    p_lis[5] = p_j_plus2(p_lis[4], sigma2, mu2)
    } 
  else if (j == 3) {
    p_lis[2] = p_j_min1(p_j, phi, sigma1, mu1)
    p_lis[1] = p_j_min2(p_lis[2], sigma1, mu1)
    p_lis[4] = p_j_plus1(p_j, phi, sigma2, mu2)
    p_lis[5] = p_j_plus2(p_lis[4], sigma2, mu2)
  }
  else if (j == 4) {
    p_lis[5] = p_j_plus1(p_j, phi, sigma2, mu2)
    p_lis[3] = p_j_min1(p_j, phi, sigma1, mu1)
    p_lis[2] = p_j_min2(p_lis[3], sigma1, mu1)
    p_lis[1] = p_j_min2(p_lis[2], sigma1, mu1)
  }
  else { # j ==5
    p_lis[4] = p_j_min1(p_j, phi, sigma1, mu1)
    p_lis[3] = p_j_min2(p_lis[4], sigma1, mu1)
    p_lis[2] = p_j_min2(p_lis[3], sigma1, mu1)
    p_lis[1] = p_j_min2(p_lis[2], sigma1, mu1)
  }
  return(p_lis)
  }
```

```{r}
get.oc(target = phi,
       p.true = p_mat[6,],
       ncohort = 10,
       cohortsize = 3,
       ntrial = 1000)
```



```{r}
p_mat = matrix(0, nrow = 10, ncol = 5)
for (i in 1:10) {
  j = sample(1:5,1)
  z_phi = qnorm(phi, 0, 1) # z(phi)
  e_j = rnorm(1, mean = z_phi, sd = sigma0)   
  p_j = pnorm(e_j, 0, 1)   # Phi(e_j)
  p_lis = rep(0,5)
  p_mat[i,] = prob_list(j,p_j,p_lis,phi,sigma1,sigma2,mu1,mu2)
}
```

```{r}
xdata = 1:5

plot(xdata, p_mat[1,], type="o", pch="o", lty=1, ylim=c(0,1),
     xlab="Dose level",
     ylab="Toxicity probability")
abline(h=0.25, col="blue")
for (i in 2:10) {
  points(xdata, p_mat[i,], pch="o")
  lines(xdata, p_mat[i,], lty=2)
}

```

